/**
 * @essrt/model-values — the rendered ESSRT display values.
 *
 * MODEL_VALUES maps key → rendered string, exactly as the 3d model-values
 * registry (tools/docs/model-values.mjs) resolves them from the engine and
 * the provenance-gated campaign artifacts. Generated by
 * tools/docs/export-model-values-package.mjs --write; the check chain fails
 * if this file drifts from the live registry.
 */

import generated from './model-values.generated.json' with { type: 'json' };

/** @type {Record<string, string>} */
export const MODEL_VALUES = generated.values;

/** Generation metadata: modelVersion, coefficients hash, key count. */
export const MODEL_VALUES_META = generated._meta;
