#!/usr/bin/env node
/**
 * STAGE-C OBLIQUITY-HYBRID VERDICT — the governed artifact (plan 02 §8,
 * Stage C / K8b-3 opening result; the C-1 publish leg).
 *
 * WRITES data/obliquity-hybrid-verdict.json (tracked; --write only) by
 * running the one-home lab tools/explore/stage-c-obliquity-hybrid.mjs
 * (--json) — ε(t) from the single averaged precession equation with the
 * orbit plane from ENGINE D (the deep ζ-modes of
 * data/nbody-deep-secular-modes.json, anchored at the JPL J2000 seed) and
 * ONE engine-K anchor, α = (H/13 rate)/cos ε₀. ZERO fitted constants.
 *
 * WHAT THE ARTIFACT HOLDS (the registry's Stage-C keys read it): the
 * derived dε/dt(J2000) beside the IAU reference the shipped scene A-solve
 * TARGETS (an input become an output); the ε(t)-vs-La2004 window table for
 * BOTH ζ depths (the two-tier verdict: the top-8 slice owns the era
 * window, the full table owns deep time — the same era-vs-deep tension the
 * e-story measured); the derived H/8 beat |ψ̇| − |s₃|; α and the H/13 rate.
 * La2004 is a THEORY reference label, never an input.
 *
 * ASSERTIONS UNDER --write:
 *   - the derived rate within 1% of the IAU reference (read from the
 *     shared astro reference — E20, never retyped);
 *   - the H/8 beat inside 40–42.5 kyr;
 *   - the era-slice 13-kyr rms beats the shipped fitted law's.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const { ROOT, buildInputsBlock } = require('../lib/artifact-inputs');
const C = require('../lib/constants.js');

const WRITE = process.argv.includes('--write');
const OUT = path.join(ROOT, 'data', 'obliquity-hybrid-verdict.json');
const LAB = 'tools/explore/stage-c-obliquity-hybrid.mjs';

if (!WRITE) {
  if (!fs.existsSync(OUT)) { console.log('no artifact yet — run with --write'); process.exit(0); }
  const art = JSON.parse(fs.readFileSync(OUT, 'utf8'));
  console.log('data/obliquity-hybrid-verdict.json — current artifact');
  console.log(`  derived deps/dt(J2000) ${art.verdict.rateEraArcsecPerCy.toFixed(2)} ″/cy era-tier (IAU ref ${art.verdict.iauRateArcsecPerCy}); H/8 beat ${art.verdict.beatKyr.toFixed(1)} kyr`);
  console.log(`  era slice 0–13 kyr: ${art.verdict.windowsEra['13'].hybridRmsArcsec.toFixed(0)}″ vs fitted law ${art.verdict.windowsEra['13'].fittedLawRmsArcsec.toFixed(0)}″`);
  console.log('  (generator class — a plain run only prints; --write re-runs the lab)');
  process.exit(0);
}

console.log('running the one-home lab (two ζ-depth integrations, ~1 min) …');
const out = execFileSync('node', [path.join(ROOT, LAB), '--json'], { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 });
const line = out.split('\n').find((l) => l.startsWith('@@OBLIQUITY_HYBRID_JSON@@ '));
if (!line) { console.error('REFUSING: no @@OBLIQUITY_HYBRID_JSON@@ line in the lab output'); process.exit(1); }
const lab = JSON.parse(line.slice('@@OBLIQUITY_HYBRID_JSON@@ '.length));

const iauRate = C.ASTRO_REFERENCE.obliquityRate_arcsecPerCentury;   // the one home (E20)
// The J2000-LOCAL rate is an ERA-tier quantity (the two-tier doctrine): the
// deep table's extra multiplet terms shift the anchored remainder near t=0
// (measured: full-table local slope −38.5 vs the era slice's −46.96), so
// the derivation claim is asserted on the ERA slice.
if (Math.abs(lab.rateEraArcsecPerCy - iauRate) > Math.abs(iauRate) * 0.01) {
  console.error(`REFUSING: derived era-tier rate ${lab.rateEraArcsecPerCy.toFixed(2)} not within 1% of the IAU reference ${iauRate}`);
  process.exit(1);
}
if (!(lab.beatKyr >= 40 && lab.beatKyr <= 42.5)) {
  console.error(`REFUSING: derived H/8 beat ${lab.beatKyr.toFixed(1)} kyr outside 40–42.5`);
  process.exit(1);
}
const era13 = lab.windowsEra['13'];
if (!(era13.hybridRmsArcsec < era13.fittedLawRmsArcsec)) {
  console.error(`REFUSING: era-slice 13-kyr rms ${era13.hybridRmsArcsec.toFixed(0)}″ does not beat the fitted law's ${era13.fittedLawRmsArcsec.toFixed(0)}″`);
  process.exit(1);
}

const art = {
  _description: 'Stage-C obliquity-hybrid verdict — ε(t) from ds/dt = α(ŝ·n̂)(ŝ×n̂) with the orbit plane from engine D (the deep ζ-modes of nbody-deep-secular-modes.json, JPL-seed anchored) and ONE engine-K anchor α = (H/13 rate)/cos ε₀; ZERO fitted constants. The derived dε/dt(J2000) sits beside the IAU reference the shipped scene A-solve TARGETS; the window tables (vs La2004, a THEORY reference label) carry BOTH ζ depths — the two-tier verdict (era slice vs full deep table). GENERATED by tools/verify/obliquity-hybrid.js --write, which runs the one-home lab tools/explore/stage-c-obliquity-hybrid.mjs. See the plan 02 §8 Stage-C record for the discovery measurements and the convention catch.',
  verdict: {
    alphaArcsecPerYr: lab.alphaArcsecPerYr,
    psiDotH13ArcsecPerYr: lab.psiDotH13ArcsecPerYr,
    rateFullArcsecPerCy: lab.rateFullArcsecPerCy,
    rateEraArcsecPerCy: lab.rateEraArcsecPerCy,
    iauRateArcsecPerCy: iauRate,
    beatKyr: lab.beatKyr,
    zetaTermsFull: lab.zetaTermsFull,
    zetaTermsEra: lab.zetaTermsEra,
    windowsFull: lab.windowsFull,
    windowsEra: lab.windowsEra,
  },
  inputs: buildInputsBlock('node tools/verify/obliquity-hybrid.js --write', [
    'tools/verify/obliquity-hybrid.js',
    'tools/explore/stage-c-obliquity-hybrid.mjs',
    'data/nbody-deep-secular-modes.json',
    'data/la2004-earth-51myr-back.asc',
  ]),
};
fs.writeFileSync(OUT, JSON.stringify(art, null, 1) + '\n');
console.log(`✓ wrote data/obliquity-hybrid-verdict.json — era-tier rate ${lab.rateEraArcsecPerCy.toFixed(2)} ″/cy (IAU ${iauRate}), beat ${lab.beatKyr.toFixed(1)} kyr, era 13-kyr ${era13.hybridRmsArcsec.toFixed(0)}″ vs law ${era13.fittedLawRmsArcsec.toFixed(0)}″`);
